### PR TITLE
Clap v4

### PR DESCRIPTION
**Pull request by chevdor**
Some vulnerabilities are reported on this repo, mainly due to old deps.
None of the vuln is serious but it generates noise.

Not sure if this project is still used. If not, we should archive it.
@jsdw @Morganamilo ?

This PR brings:
- deps update (incl. `toml_edit`) 
- update to clap v4
- version bump to v0.2.0
- an fmt pass

This PR should make #7, #8 and #15 no longer relevant.

### CODE REVIEW

**Comment by jsdw** [comment]
It's still used on occasion; thankyou for the dependency updates!

I'd prefer spaces to tabs in the formatting though (I thought that was the default; strange!)

**Comment by chevdor** [comment]
> It's still used on occasion; thankyou for the dependency updates!

Ok so no archiving. This is not a problem as long as the deps are updated no vuln. is reported :)

> I'd prefer spaces to tabs in the formatting though (I thought that was the default; strange!)

I can double check but I think I am using the substrate default rustfmt config accross all projects.
If you prefer another variation, best would be to add your rustfmt config in the repo so local rustfmt runs would comply with your prefs.

**Comment by chevdor** [comment]
I can fix the fmt in this PR if you have a config at hand.

Or we merge it as is, you add a rustfmt config later on, and we do a new pass to fix everything again.

**Comment by jsdw** [comment]
> I can double check but I think I am using the substrate default rustfmt config accross all projects.

Aah, my concern there then is that if somebody else eg from my team comes to this project and runs `cargo fmt` then it would reformat everything to the rust defaults, which are quite different. So I'd rather it was just formatted with rust default rules for consistency :)

I don't actually know whether we have any companywide expectation that people will use any specific formatting rules by default though; maybe there is and I've just been blissfully unaware!

(side note: I don't generally care about tabs vs spaces, but in rust I've found that doc examples can be annoying to work with when tabs are involved, because they expect 1 space from the `///` and then tabs afterwards)

**Comment by chevdor** [comment]
> I don't actually know whether we have any companywide expectation that people will use any specific formatting rules by default though; maybe there is and I've just been blissfully unaware!

This is why I am using the settings from Substrate. I know there are being ported to Polkadot and Cumulus as well.
I think those will be closer to what we want at Parity than the Rust defaults.

That being said, I personnally don't care too much and the best option would really be to have the settings in the repo, this way, there is no ambiguity and if the "Substrate" settings are not optimuim for the repo, they can be adjusted at wish.

I can propose adding [the substrate settings](https://github.com/paritytech/substrate/blob/master/rustfmt.toml) as well as the [editorconfig](https://github.com/paritytech/substrate/blob/master/.editorconfig). That should align everyone. 

I would then **remove the fmt changes** from this PR and make another PR for the formatting stuff.
Does it sound good ?

**Comment by chevdor** [comment]
See #17

**Review by jsdw — APPROVED** [review]

**Comment by jsdw** [comment]
Perfect, yup separting the formatting makes sense and makes this easy to approve :)

**Pull request merged**
